#!/usr/bin/env python3
"""BUILD-PLAN step 1 — verify the three ADK contracts `agents/fleet.py` hangs off.

    python scripts/adk_spike.py            # contract probes; no credentials needed
    python scripts/adk_spike.py --live     # additionally call Gemini for real

The load-bearing one is the short-circuit: `governance/gate.py` holds a
consequential call by RETURNING A DICT from `before_tool_callback` and trusting
ADK to skip the tool body. If that were false the gate would log a hold and then
let the write happen anyway — the failure mode that looks green and is not.

So the probe does not ask ADK whether it skipped; it asks the TOOL. Each tool
body appends to `TOOL_BODY_RUNS` before doing its work, and a body that did not
run cannot have left a record. That is the whole proof, and it is why this script
drives a real `Runner` over a real `LlmAgent` instead of calling the callback
directly — calling the callback directly would only prove that our own function
returns a dict, which was never in doubt.

The model is scripted rather than live because the contract under test is ADK's
tool dispatch, not Gemini's judgment. `--live` covers the other half of the done
test (a real model quoting a real figure) and needs credentials.
"""

from __future__ import annotations

import argparse
import asyncio
import os
import sys
from collections.abc import AsyncGenerator
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

os.environ.setdefault("FREIGHT_WORKSPACE_ROOT", str(ROOT / "workspace"))

from google.adk.agents import LlmAgent
from google.adk.models.base_llm import BaseLlm
from google.adk.models.llm_request import LlmRequest
from google.adk.models.llm_response import LlmResponse
from google.adk.runners import Runner
from google.adk.sessions import InMemorySessionService
from google.adk.tools import FunctionTool
from google.genai import types
from pydantic import Field

from freight_fleet.tools import workspace

WAYBILL = "shipments/shp-002-hero/waybill.md"

#: Appended to by an instrumented tool body. The only witness that matters: a
#: body that did not run cannot have left a record here.
TOOL_BODY_RUNS: list[dict[str, Any]] = []


# The shims below are spelled out rather than generated by a decorator because
# ADK builds each tool's declaration from its signature and docstring — a
# *args/**kwargs wrapper would hand the model a tool it cannot call.

def read_file(path: str) -> dict:
    """Read one workspace file as UTF-8 text.

    Args:
        path: Workspace-relative path, e.g. "shipments/shp-002-hero/waybill.md".
    """
    TOOL_BODY_RUNS.append({"tool": "read_file", "path": path})
    return workspace.read_file(path)


def list_files(prefix: str = "") -> dict:
    """List workspace files under a directory prefix.

    Args:
        prefix: Workspace-relative directory, e.g. "shipments". Empty = root.
    """
    TOOL_BODY_RUNS.append({"tool": "list_files", "prefix": prefix})
    return workspace.list_files(prefix)


def glob_files(pattern: str) -> dict:
    """Find workspace files matching a glob pattern.

    Args:
        pattern: e.g. "shipments/**/*.csv".
    """
    TOOL_BODY_RUNS.append({"tool": "glob_files", "pattern": pattern})
    return workspace.glob_files(pattern)


def grep_files(pattern: str, prefix: str = "") -> dict:
    """Search workspace file contents for a regular expression.

    Args:
        pattern: Python regular expression.
        prefix: Optional workspace-relative directory to scope the search.
    """
    TOOL_BODY_RUNS.append({"tool": "grep_files", "pattern": pattern})
    return workspace.grep_files(pattern, prefix)


def write_file(path: str, content: str) -> dict:
    """Create or overwrite a workspace file. CONSEQUENTIAL — held by the gate.

    Args:
        path: Workspace-relative path, e.g. "outbox/BK4471-notice.md".
        content: Full file body.
    """
    TOOL_BODY_RUNS.append({"tool": "write_file", "path": path})
    return workspace.write_file(path, content)


#: Every tool the fleet exposes, with arguments that would really do something
#: if the body ever ran. Keys must match `governance.policy.TOOL_SPECS`.
GATED_TOOLS: dict[str, tuple[Any, dict[str, Any]]] = {
    "read_file": (read_file, {"path": WAYBILL}),
    "list_files": (list_files, {"prefix": "shipments"}),
    "glob_files": (glob_files, {"pattern": "shipments/**/*.md"}),
    "grep_files": (grep_files, {"pattern": "MERU", "prefix": "shipments"}),
    "write_file": (write_file, {"path": "outbox/probe.md", "content": "probe"}),
}


class ScriptedLlm(BaseLlm):
    """A BaseLlm that replays fixed turns and records what it was sent.

    Standing in for Gemini keeps the probe deterministic and credential-free,
    and — more usefully — lets us read the function response ADK handed back,
    which is how we prove the model saw the gate's dict and not the file.
    """

    calls: list[LlmRequest] = Field(default_factory=list)
    turns: list[types.Content] = Field(default_factory=list)

    async def generate_content_async(
        self, llm_request: LlmRequest, stream: bool = False
    ) -> AsyncGenerator[LlmResponse, None]:
        self.calls.append(llm_request)
        idx = min(len(self.calls) - 1, len(self.turns) - 1)
        yield LlmResponse(content=self.turns[idx], turn_complete=True)


def _scripted_model() -> ScriptedLlm:
    """Turn 1 calls read_file; turn 2 reports whatever came back."""
    return ScriptedLlm(
        model="scripted-probe",
        calls=[],
        turns=[
            types.Content(
                role="model",
                parts=[types.Part(function_call=types.FunctionCall(
                    name="read_file", args={"path": WAYBILL}))],
            ),
            types.Content(role="model", parts=[types.Part(text="done")]),
        ],
    )


def _tool_response(model: ScriptedLlm) -> dict[str, Any] | None:
    """The function response ADK put in front of the model on its second turn."""
    for request in reversed(model.calls):
        for content in reversed(request.contents or []):
            for part in content.parts or []:
                if part.function_response is not None:
                    return part.function_response.response
    return None


async def _run(agent: LlmAgent, prompt: str) -> str:
    session_service = InMemorySessionService()
    await session_service.create_session(
        app_name="freight_spike", user_id="operator", session_id="spike"
    )
    runner = Runner(agent=agent, app_name="freight_spike", session_service=session_service)
    final = ""
    async for event in runner.run_async(
        user_id="operator",
        session_id="spike",
        new_message=types.Content(role="user", parts=[types.Part(text=prompt)]),
    ):
        if event.is_final_response() and event.content and event.content.parts:
            final = "".join(p.text or "" for p in event.content.parts)
    return final


async def probe_tool_runs_without_a_gate() -> dict[str, Any]:
    """Control: with no callback the tool body must run and return the document."""
    TOOL_BODY_RUNS.clear()
    model = _scripted_model()
    agent = LlmAgent(name="spike_ungated", model=model, instruction="Read the waybill.",
                     tools=[FunctionTool(read_file)])
    await _run(agent, "Read the waybill.")
    response = _tool_response(model) or {}
    return {
        "tool_body_runs": len(TOOL_BODY_RUNS),
        "status": response.get("status"),
        "content_chars": len(response.get("content") or ""),
        "has_gross_weight": "6,098.0 KGS" in (response.get("content") or ""),
    }


async def probe_short_circuit() -> dict[str, Any]:
    """The load-bearing contract: a dict from before_tool_callback skips the body."""
    return await probe_gate_sees("read_file")


async def probe_gate_sees(tool_name: str) -> dict[str, Any]:
    """Same probe as above, for one named tool: does the seam catch it at all?

    Run per tool rather than once for `read_file`, because "every tool call
    passes the gate" is a claim about the tool SURFACE, and a surface is only
    checked by enumerating it.
    """
    TOOL_BODY_RUNS.clear()
    fn, call_args = GATED_TOOLS[tool_name]
    seen: list[str] = []

    def probe_gate(tool, args: dict[str, Any], tool_context) -> dict[str, Any]:
        seen.append(getattr(tool, "name", str(tool)))
        return {"status": "test"}

    model = ScriptedLlm(
        model="scripted-probe",
        calls=[],
        turns=[
            types.Content(role="model", parts=[types.Part(
                function_call=types.FunctionCall(name=tool_name, args=call_args))]),
            types.Content(role="model", parts=[types.Part(text="done")]),
        ],
    )
    agent = LlmAgent(name=f"spike_{tool_name}", model=model, instruction="Use the tool.",
                     tools=[FunctionTool(fn)], before_tool_callback=probe_gate)
    await _run(agent, "Use the tool.")
    return {
        "callback_fired_for": seen,
        "tool_body_runs": len(TOOL_BODY_RUNS),
        "model_saw": _tool_response(model),
    }


async def probe_real_gate_holds_a_write() -> dict[str, Any]:
    """The contract as governance/gate.py actually uses it: write_file is held."""
    from freight_fleet.governance.gate import ApprovalStore, make_before_tool_gate
    from freight_fleet.governance.ledger import Ledger

    target = Path(os.environ["FREIGHT_WORKSPACE_ROOT"]) / "outbox" / "spike-must-not-exist.md"
    target.unlink(missing_ok=True)

    ledger = Ledger(ROOT / "audit" / "spike-ledger.jsonl")
    ledger.path.unlink(missing_ok=True)
    gate = make_before_tool_gate(ledger, ApprovalStore(), "spike")

    model = ScriptedLlm(
        model="scripted-probe",
        calls=[],
        turns=[
            types.Content(role="model", parts=[types.Part(function_call=types.FunctionCall(
                name="write_file",
                args={"path": "outbox/spike-must-not-exist.md", "content": "x" * 4000}))]),
            types.Content(role="model", parts=[types.Part(text="held")]),
        ],
    )
    agent = LlmAgent(name="spike_write", model=model, instruction="Draft the notice.",
                     tools=[FunctionTool(workspace.write_file)], before_tool_callback=gate)
    await _run(agent, "Draft the notice.")
    response = _tool_response(model) or {}
    rows = list(ledger.read())
    return {
        "file_created": target.exists(),
        "model_saw_status": response.get("status"),
        "ledger_outcomes": [r.outcome for r in rows],
        "ledger_args_digest": rows[-1].args_digest if rows else None,
    }


async def probe_live(model_name: str) -> dict[str, Any]:
    """The other half of the done test: a real model quoting a real figure."""
    TOOL_BODY_RUNS.clear()
    agent = LlmAgent(
        name="spike_live",
        model=model_name,
        instruction=(
            "You read freight documents. Use read_file to read the path the operator "
            "names. Quote figures exactly as printed; never infer a document's contents."
        ),
        tools=[FunctionTool(read_file)],
    )
    text = await _run(
        agent,
        f"Read {WAYBILL} and tell me the gross weight, the container number, "
        "and whether freight is prepaid or collect.",
    )
    return {
        "tool_body_runs": len(TOOL_BODY_RUNS),
        "final_text": text,
        "quotes_gross_weight": "6,098" in text,
        "quotes_container": "MERU5502312" in text,
    }


def _verdict(ok: bool) -> str:
    return "HOLDS" if ok else "BROKEN"


async def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--live", action="store_true", help="also call Gemini for real")
    ap.add_argument("--model", default=os.environ.get("FREIGHT_MODEL", "gemini-2.5-pro"))
    args = ap.parse_args()

    root = Path(os.environ["FREIGHT_WORKSPACE_ROOT"])
    if not (root / WAYBILL).is_file():
        print(f"  workspace not seeded: {root / WAYBILL} missing")
        print("  run: python scripts/seed_workspace.py")
        return 2

    import google.adk
    print(f"\n  google-adk {google.adk.__version__}   workspace {root}\n")
    failures = 0

    control = await probe_tool_runs_without_a_gate()
    ok = control["tool_body_runs"] == 1 and control["has_gross_weight"]
    failures += not ok
    print(f"  [control] no callback -> tool body runs                     {_verdict(ok)}")
    print(f"            body ran {control['tool_body_runs']}x, returned {control['content_chars']} chars, "
          f"gross weight present: {control['has_gross_weight']}\n")

    sc = await probe_short_circuit()
    ok = sc["tool_body_runs"] == 0 and sc["model_saw"] == {"status": "test"}
    failures += not ok
    print(f"  [1] dict from before_tool_callback short-circuits the body  {_verdict(ok)}")
    print(f"      callback fired for {sc['callback_fired_for']}")
    print(f"      TOOL BODY EXECUTIONS: {sc['tool_body_runs']}   (must be 0)")
    print(f"      model received: {sc['model_saw']}\n")

    sweep = {name: await probe_gate_sees(name) for name in sorted(GATED_TOOLS)}
    missed = [n for n, r in sweep.items()
              if r["callback_fired_for"] != [n] or r["tool_body_runs"] != 0]
    ok = not missed
    failures += not ok
    print(f"  [1a] every tool in the surface reaches the seam              {_verdict(ok)}")
    for name, r in sweep.items():
        print(f"       {name:12} callback fired: {r['callback_fired_for'] == [name]}   "
              f"body ran: {r['tool_body_runs']}x")
    print()

    gate = await probe_real_gate_holds_a_write()
    ok = (not gate["file_created"]
          and gate["model_saw_status"] == "pending_approval"
          and gate["ledger_outcomes"] == ["held"])
    failures += not ok
    print(f"  [1b] the real gate holds write_file end to end              {_verdict(ok)}")
    print(f"       file created on disk: {gate['file_created']}   (must be False)")
    print(f"       model received status: {gate['model_saw_status']}")
    print(f"       ledger: {gate['ledger_outcomes']}  digest {gate['ledger_args_digest']}\n")

    if args.live:
        try:
            live = await probe_live(args.model)
            ok = live["tool_body_runs"] >= 1 and live["quotes_gross_weight"]
            failures += not ok
            print(f"  [live] {args.model} reads the waybill                {_verdict(ok)}")
            print(f"         tool body ran {live['tool_body_runs']}x, "
                  f"quotes 6,098: {live['quotes_gross_weight']}, "
                  f"quotes container: {live['quotes_container']}")
            print(f"\n--- model output ---\n{live['final_text']}\n--- end ---\n")
        except Exception as exc:  # noqa: BLE001 - the point is to report it verbatim
            failures += 1
            print(f"  [live] {args.model}                                          FAILED")
            print(f"         {type(exc).__name__}: {str(exc)[:300]}\n")

    print(f"  {'ALL CONTRACTS HOLD' if not failures else f'{failures} CONTRACT(S) BROKEN'}\n")
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(asyncio.run(main()))
